import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { extractPdfText } from "../src/extraction/pdf-text.js";

describe("extractPdfText", () => {
  it("extracts the full embedded text layer from a digital PDF", async () => {
    const bytes = new Uint8Array(await readFile("test/fixtures/digital-invoice.pdf"));
    const result = await extractPdfText(bytes);

    expect(result.pageCount).toBe(1);
    expect(result.text).toContain("Riverbend Supply Co.");
    expect(result.text).toContain("INV-10492");
    expect(result.text).toContain("698.76");
  });

  it("extracts nothing from a scanned/image-only PDF — no embedded text layer to read", async () => {
    const bytes = new Uint8Array(await readFile("test/fixtures/scanned-invoice.pdf"));
    const result = await extractPdfText(bytes);

    expect(result.pageCount).toBe(1);
    expect(result.text.trim()).toBe("");
  });

  // Phase 3 item 16 (failure isolation): both fixtures are real files, not
  // mocked errors — generated by test/fixtures/generate-failure-fixtures.py.
  // Confirms a corrupt or locked upload fails loudly and immediately
  // rather than hanging or silently returning garbage, so the worker's
  // per-document try/catch (worker/src/tick.ts) has a clear error to catch
  // and route to a 'failed' status instead of blocking the queue.
  it("throws clearly on a corrupt/malformed PDF rather than hanging or returning garbage", async () => {
    const bytes = new Uint8Array(await readFile("test/fixtures/corrupt-invoice.pdf"));
    await expect(extractPdfText(bytes)).rejects.toThrow();
  });

  it("throws clearly on a password-locked PDF rather than hanging or returning garbage", async () => {
    const bytes = new Uint8Array(await readFile("test/fixtures/locked-invoice.pdf"));
    await expect(extractPdfText(bytes)).rejects.toThrow();
  });
});
